name: Publish documentation
on:
  push:
    branches:
      - main  # Автоматическая сборка при отправке кода в ветку main
  workflow_dispatch: # Добавляет кнопку ручного запуска ("ручку") в интерфейс GitHub

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5  # <-- Обновили до v5

      - name: Set up Python
        uses: actions/setup-python@v6  # <-- Обновили до v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install mkdocs-material

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force